export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const MASJID_ID_SETTER = "MASJID_ID_SETTER";

export const CHANGE_SNACKBAR = "CHANGE_SNACKBAR";

export const FETCH_LATEST_UPDATED_EVENTS_BY_ADMIN =
  "FETCH_LATEST_UPDATED_EVENTS_BY_ADMIN";

export const FETCH_LATEST_UPDATED_ANNOUNCEMENTS_BY_ADMIN =
  "FETCH_LATEST_UPDATED_ANNOUNCEMENTS_BY_ADMIN";

export const FETCH_ADMIN_MASJID = "FETCH_ADMIN_MASJID";

export const FETCH_ALL_MASJID = "FETCH_ALL_MASJID";

export const GET_TIMINGS_BY_DATE_RANGE = "GET_TIMINGS_BY_DATE_RANGE";

export const COMPLETE_EVENT_EDITING = "COMPLETE_EVENT_EDITING";

// ActionTypes.ts
export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_NEARBY_MASJIDS = "FETCH_NEARBY_MASJIDS";
